version: '3.8'

services:
  trello:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: trello:latest
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    container_name: Trello
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: gozzog
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cykard
    volumes:
      - ./export.sql:/docker-entrypoint-initdb.d/export.sql
    command: [ "postgres", "-c", "max_connections=200" ]
    ports:
      - "5432:5432"
    container_name: Postgres