create table doctrine_migration_versions
(
    version        varchar(191) not null
        primary key,
    executed_at    timestamp(0) default NULL::timestamp without time zone,
    execution_time integer
);

alter table doctrine_migration_versions
    owner to gozzog;

create table messenger_messages
(
    id           bigint generated by default as identity
        primary key,
    body         text         not null,
    headers      text         not null,
    queue_name   varchar(190) not null,
    created_at   timestamp(0) not null,
    available_at timestamp(0) not null,
    delivered_at timestamp(0) default NULL::timestamp without time zone
);

alter table messenger_messages
    owner to gozzog;

create index idx_75ea56e0fb7336f0
    on messenger_messages (queue_name);

create index idx_75ea56e0e3bd61ce
    on messenger_messages (available_at);

create index idx_75ea56e016ba31db
    on messenger_messages (delivered_at);

create table "user"
(
    login       varchar(180) not null,
    roles       json         not null,
    password    varchar(255) not null,
    nom         varchar(255) default NULL::character varying,
    prenom      varchar(255) default NULL::character varying,
    email       varchar(255) not null,
    is_verified boolean      not null,
    id          integer generated by default as identity
        primary key,
    api_token   varchar(255) default NULL::character varying
);

alter table "user"
    owner to gozzog;

create table tableau
(
    id           integer generated by default as identity
        primary key,
    codetableau  varchar(255) not null,
    titretableau varchar(50)  not null
);

alter table tableau
    owner to gozzog;

create table colonne
(
    id           integer generated by default as identity
        primary key,
    titrecolonne varchar(50) not null,
    tableau_id   integer     not null
        constraint fk_65f87c44b062d5bc
            references tableau
);

alter table colonne
    owner to gozzog;

create table carte
(
    id              integer generated by default as identity
        primary key,
    titrecarte      varchar(50) not null,
    descriptifcarte text,
    couleurcarte    varchar(7)  not null,
    colonne_id      integer     not null
        constraint fk_bad4fffd213eac9d
            references colonne
);

alter table carte
    owner to gozzog;

create index idx_bad4fffd213eac9d
    on carte (colonne_id);

create index idx_65f87c44b062d5bc
    on colonne (tableau_id);

create table user_carte
(
    user_id  integer not null
        constraint fk_581604a5a76ed395
            references "user"
            on delete cascade,
    carte_id integer not null
        constraint fk_581604a5c9c7ceb6
            references carte
            on delete cascade,
    primary key (user_id, carte_id)
);

alter table user_carte
    owner to gozzog;

create index idx_581604a5a76ed395
    on user_carte (user_id);

create index idx_581604a5c9c7ceb6
    on user_carte (carte_id);

create table user_tableau
(
    user_id    integer not null
        constraint fk_9e7953bba76ed395
            references "user"
            on delete cascade,
    tableau_id integer not null
        constraint fk_9e7953bbb062d5bc
            references tableau
            on delete cascade,
    primary key (user_id, tableau_id)
);

alter table user_tableau
    owner to gozzog;

create index idx_9e7953bba76ed395
    on user_tableau (user_id);

create index idx_9e7953bbb062d5bc
    on user_tableau (tableau_id);

