parameters:
  kernel.secret: 'cf2e819d173f6f2d9d0c8581fd4b8944ceaddbb899a5828a41a38d6dd354b715'

services:
  routing.loader:
    class: App\Lib\Route\AttributeRouteControllerLoader

  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'

  App\Lib\Database\Database:
    arguments:
      - '@pdo'
  pdo:
    class: PDO
    arguments:
      - '%env(resolve:DATABASE_URL_2)%'

  App\Lib\Security\UserConnection\UserExtension:
    tags:
      - { name: twig.extension }

  App\Lib\Security\RateLimiter\RateLimiter:
    arguments: [ 800, 7200 ]

  App\Lib\Security\RateLimiter\RateLimitListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request }

